### ISSUE TITLE
Package makes the query slower than just using standard Laravel

### ISSUE THREAD

**Issue by marky291** [staudenmeir/eloquent-eager-limit#46]
<img width="455" alt="Screenshot 2021-09-25 at 12 43 42" src="https://user-images.githubusercontent.com/5384515/134770300-b3ad47f6-e27e-4681-aae9-31cdcd15d682.png">
<img width="495" alt="Screenshot 2021-09-25 at 12 44 02" src="https://user-images.githubusercontent.com/5384515/134770304-e36b808d-ada0-4292-80b8-c3620d5ff316.png">
<img width="483" alt="Screenshot 2021-09-25 at 12 44 24" src="https://user-images.githubusercontent.com/5384515/134770305-a67b8d98-ded6-43cf-8182-8f034d51595b.png">

**Comment by staudenmeir** [comment]
Two things:
- Due to the more complex query, the package is not faster in every use case. Depending on the database size and especially the distribution of records (in your case number of responses per monitor), there's a threshold where the package gets the upper hand.
- You need to consider more than the query runtime: It also takes time for Laravel to hydrate the Eloquent models from the query results. For big result sets, this can take quite a while.

**Comment by marky291** [comment]
Thanks for reply, I was thinking with a bigger database it would maybe come out faster, for now I only have 60 records on local, used to test this specifically which is maybe my issue. I no longer have a doubt regarding this package and will seed and test with more records.
